<?php

namespace Database\Seeders;

use App\Contracts\PermissionRegistryContract;
use Illuminate\Database\Seeder;

/**
 * Permission Seeder
 * 
 * Phase 2: Registry-first + Audit-first implementation
 * ALL permissions MUST be registered here before they can be used
 * 
 * This is the SINGLE SOURCE OF TRUTH for all permissions in the system
 */
class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        /** @var PermissionRegistryContract $registry */
        $registry = app(PermissionRegistryContract::class);

        $this->command->info('🔐 Registering permissions (Registry-first)...');

        // Register all permissions (Phase 2 baseline)
        $this->registerAuthPermissions($registry);
        $this->registerUserPermissions($registry);
        $this->registerRolePermissions($registry);
        
        // Phase 7: Product CRUD permissions (generated by CRUD generator)
        $this->registerProductPermissions($registry);

        // Phase 8: Menu Builder permissions
        $this->registerMenuPermissions($registry);

        // Sync to database
        $stats = $registry->syncToDatabase();

        $this->command->info("✅ Permissions synced: {$stats['created']} created, {$stats['updated']} updated");

        // Audit-first: Log permission sync
        logger()->info('Permissions seeded', [
            'created' => $stats['created'],
            'updated' => $stats['updated'],
            'total' => count($registry->all()),
        ]);
    }

    /**
     * Register authentication-related permissions
     */
    protected function registerAuthPermissions(PermissionRegistryContract $registry): void
    {
        $registry->registerMany([
            'auth.login' => [
                'group' => 'Authentication',
                'description' => 'Can log in to the system',
            ],
            'auth.logout' => [
                'group' => 'Authentication',
                'description' => 'Can log out from the system',
            ],
        ]);
    }

    /**
     * Register user management permissions
     */
    protected function registerUserPermissions(PermissionRegistryContract $registry): void
    {
        $registry->registerMany([
            'users.view' => [
                'group' => 'Users',
                'description' => 'Can view users list',
            ],
            'users.create' => [
                'group' => 'Users',
                'description' => 'Can create new users',
            ],
            'users.edit' => [
                'group' => 'Users',
                'description' => 'Can edit existing users',
            ],
            'users.delete' => [
                'group' => 'Users',
                'description' => 'Can delete users',
            ],
        ]);
    }

    /**
     * Register role management permissions
     */
    protected function registerRolePermissions(PermissionRegistryContract $registry): void
    {
        $registry->registerMany([
            'roles.view' => [
                'group' => 'Roles',
                'description' => 'Can view roles list',
            ],
            'roles.create' => [
                'group' => 'Roles',
                'description' => 'Can create new roles',
            ],
            'roles.edit' => [
                'group' => 'Roles',
                'description' => 'Can edit existing roles',
            ],
            'roles.delete' => [
                'group' => 'Roles',
                'description' => 'Can delete roles',
            ],
        ]);
    }

    /**
     * Register menu-related permissions (Phase 8)
     */
    protected function registerMenuPermissions(PermissionRegistryContract $registry): void
    {
        $registry->registerMany([
            'menu.view' => [
                'group' => 'Menus',
                'description' => 'Can view menu builder',
            ],
            'menu.create' => [
                'group' => 'Menus',
                'description' => 'Can create menu items',
            ],
            'menu.update' => [
                'group' => 'Menus',
                'description' => 'Can update menu items',
            ],
            'menu.delete' => [
                'group' => 'Menus',
                'description' => 'Can delete menu items',
            ],
        ]);
    }

    /**
     * Register product-related permissions (Phase 7)
     */
    protected function registerProductPermissions(PermissionRegistryContract $registry): void
    {
        $registry->registerMany([
            'product.view' => [
                'group' => 'Products',
                'description' => 'Can view products',
            ],
            'product.create' => [
                'group' => 'Products',
                'description' => 'Can create products',
            ],
            'product.update' => [
                'group' => 'Products',
                'description' => 'Can update products',
            ],
            'product.delete' => [
                'group' => 'Products',
                'description' => 'Can delete products',
            ],
        ]);
    }
}
