<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\MenuController;

// Phase 8: Menu Builder routes (admin, auth + tenant + permission protected)
Route::middleware(['auth', 'tenant.selected'])
    ->prefix('admin')
    ->name('admin.')
    ->group(function () {
        // Menu builder index (view)
        Route::get('menu', [MenuController::class, 'index'])
            ->middleware('permission:menu.view')
            ->name('menu.index');

        // Menu groups (create/update/delete)
        Route::post('menu/groups', [MenuController::class, 'storeGroup'])
            ->middleware('permission:menu.create')
            ->name('menu.groups.store');
        Route::put('menu/groups/{group}', [MenuController::class, 'updateGroup'])
            ->middleware('permission:menu.update')
            ->name('menu.groups.update');
        Route::delete('menu/groups/{group}', [MenuController::class, 'destroyGroup'])
            ->middleware('permission:menu.delete')
            ->name('menu.groups.destroy');

        // Menu items (create/update/delete)
        Route::post('menu/items', [MenuController::class, 'storeItem'])
            ->middleware('permission:menu.create')
            ->name('menu.items.store');
        Route::put('menu/items/{item}', [MenuController::class, 'updateItem'])
            ->middleware('permission:menu.update')
            ->name('menu.items.update');
        Route::delete('menu/items/{item}', [MenuController::class, 'destroyItem'])
            ->middleware('permission:menu.delete')
            ->name('menu.items.destroy');

        // Reorder (Phase 8.4) — requires update permission
        Route::get('menu/items/{item}/move-up', [MenuController::class, 'moveUp'])
            ->middleware('permission:menu.update')
            ->name('menu.items.moveUp');
        Route::get('menu/items/{item}/move-down', [MenuController::class, 'moveDown'])
            ->middleware('permission:menu.update')
            ->name('menu.items.moveDown');

        // Cache management — requires update permission
        Route::get('menu/clear-cache', [MenuController::class, 'clearCache'])
            ->middleware('permission:menu.update')
            ->name('menu.clearCache');
    });

// Product CRUD (generated by neonex:make:crud) — permission protected
Route::middleware(['auth', 'tenant.selected'])
    ->prefix('admin')
    ->name('admin.')
    ->group(function () {
        Route::get('product', [\App\Http\Controllers\Admin\ProductController::class, 'index'])
            ->middleware('permission:product.view')
            ->name('product.index');
        Route::get('product/create', [\App\Http\Controllers\Admin\ProductController::class, 'create'])
            ->middleware('permission:product.create')
            ->name('product.create');
        Route::post('product', [\App\Http\Controllers\Admin\ProductController::class, 'store'])
            ->middleware('permission:product.create')
            ->name('product.store');
        Route::get('product/{product}', [\App\Http\Controllers\Admin\ProductController::class, 'show'])
            ->middleware('permission:product.view')
            ->name('product.show');
        Route::get('product/{product}/edit', [\App\Http\Controllers\Admin\ProductController::class, 'edit'])
            ->middleware('permission:product.update')
            ->name('product.edit');
        Route::put('product/{product}', [\App\Http\Controllers\Admin\ProductController::class, 'update'])
            ->middleware('permission:product.update')
            ->name('product.update');
        Route::delete('product/{product}', [\App\Http\Controllers\Admin\ProductController::class, 'destroy'])
            ->middleware('permission:product.delete')
            ->name('product.destroy');
    });
