<?php

use Illuminate\Support\Facades\Route;

// Generated routes

// Product CRUD (generated by neonex:make:crud)
Route::middleware(['auth', 'tenant.selected'])
    ->prefix('admin')
    ->name('admin.')
    ->group(function () {
        Route::resource('product', \App\Http\Controllers\Admin\ProductController::class);
    });
