<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\MenuController;

// Phase 8: Menu Builder routes (admin, auth + tenant protected)
Route::middleware(['auth', 'tenant.selected'])
    ->prefix('admin')
    ->name('admin.')
    ->group(function () {
        // Menu builder index
        Route::get('menu', [MenuController::class, 'index'])->name('menu.index');

        // Menu groups
        Route::post('menu/groups', [MenuController::class, 'storeGroup'])->name('menu.groups.store');
        Route::put('menu/groups/{group}', [MenuController::class, 'updateGroup'])->name('menu.groups.update');
        Route::delete('menu/groups/{group}', [MenuController::class, 'destroyGroup'])->name('menu.groups.destroy');

        // Menu items
        Route::post('menu/items', [MenuController::class, 'storeItem'])->name('menu.items.store');
        Route::put('menu/items/{item}', [MenuController::class, 'updateItem'])->name('menu.items.update');
        Route::delete('menu/items/{item}', [MenuController::class, 'destroyItem'])->name('menu.items.destroy');

        // Reorder (Phase 8.4)
        Route::get('menu/items/{item}/move-up', [MenuController::class, 'moveUp'])->name('menu.items.moveUp');
        Route::get('menu/items/{item}/move-down', [MenuController::class, 'moveDown'])->name('menu.items.moveDown');

        // Cache management
        Route::get('menu/clear-cache', [MenuController::class, 'clearCache'])->name('menu.clearCache');
    });

// Product CRUD (generated by neonex:make:crud)
Route::middleware(['auth', 'tenant.selected'])
    ->prefix('admin')
    ->name('admin.')
    ->group(function () {
        Route::resource('product', \App\Http\Controllers\Admin\ProductController::class);
    });
