<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Admin\ProductRequest;
use App\Models\Product;

/**
 * ProductController
 * 
 * Generated by neonex:make:crud (Phase 7)
 * - Tenant-aware CRUD
 * - AJAX-friendly delete
 * - Plain Bootstrap views
 */
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $query = Product::query()->where('tenant_id', tenant_id());

        // Search functionality
        if ($search = $request->string('search')->toString()) {
            $query->where(function ($q) use ($search) {
                $q->where('id', 'like', "%{$search}%")

                  ->orWhere('name', 'like', "%{$search}%");
            });
        }

        // Server-side pagination (keep it simple first)
        $products = $query->latest()->paginate(25)->withQueryString();

        return view('admin.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.product.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(ProductRequest $request)
    {
        $data = $request->validated();
        $data['tenant_id'] = tenant_id();

        Product::create($data);

        // Audit logging
        audit()->record('product.created', [
            'model' => 'Product',
            'data' => $data,
        ]);

        return redirect()->route('admin.product.index')
            ->with('success', 'Product created successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Product $product)
    {
        // Tenant safety check
        abort_if($product->tenant_id !== tenant_id(), 403);
        
        return view('admin.product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(ProductRequest $request, Product $product)
    {
        // Tenant safety check
        abort_if($product->tenant_id !== tenant_id(), 403);
        
        $product->update($request->validated());

        // Audit logging
        audit()->record('product.updated', [
            'model' => 'Product',
            'id' => $product->id,
        ]);

        return redirect()->route('admin.product.index')
            ->with('success', 'Product updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $product)
    {
        // Tenant safety check
        abort_if($product->tenant_id !== tenant_id(), 403);
        
        $product->delete();

        // Audit logging
        audit()->record('product.deleted', [
            'model' => 'Product',
            'id' => $product->id,
        ]);

        // AJAX-friendly response
        if (request()->expectsJson()) {
            return response()->json(['ok' => true, 'message' => 'Product deleted successfully.']);
        }

        return redirect()->route('admin.product.index')
            ->with('success', 'Product deleted successfully.');
    }
}
